name: equipamentos

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - '5431:5432'
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=equipamentos